name: Upstream (TWRP)

on:
  push:
    branches:
      - twrp-master

jobs:
  build:
    name: Automatic upstream
    runs-on: ubuntu-16.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Upstream branches
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/"${GITHUB_USER}"/releases.git
        cd releases
        git checkout twrp-master
        function upstream() { for var in twrp-cactus twrp-cedric twrp-cereus twrp-montana; do git checkout twrp-master; git checkout -b $var; git cherry-pick origin/$var; git push -f -u origin $var; done; git checkout twrp-master; }
        upstream
      env:
        GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_KEY }}
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
